-- CRIAÇÃO DA TABELA SUBSTÂNCIA
CREATE TABLE Substancia(
  	Cod_Subst INTEGER NOT NULL,
  	Nome_Subst VARCHAR(45) NOT NULL,
  	CONSTRAINT Pk_Substancia PRIMARY KEY (Cod_Subst)
 );

-- CRIAÇÃO DA TABELA COMPOSIÇÃO
CREATE TABLE Composicao(
  	Cod_Comp INTEGER NOT NULL,
  	Principio_Ativo VARCHAR(45) NOT NULL,
  	CONSTRAINT Pk_Composicao PRIMARY KEY (Cod_Comp)
 );

-- CRIAÇÃO DA TABELA COMPOSIÇÃO_HAS_SUBSTANCIA
-- GERADA A PARIR DA RELAÇAO NxN DE COMPOSIÇÃO E SUBSTANCIA
CREATE TABLE Composicao_has_Substancia(
   	Composicao_Cod_Comp INTEGER NOT NULL,
   	Substancia_Cod_Subst INTEGER NOT NULL,
   	Quantidade INTEGER NOT NULL,
   	CONSTRAINT Pk_Composicao_has_Substancia PRIMARY KEY (Composicao_Cod_Comp, Substancia_Cod_Subst)
 );

-- CRIAÇÃO DA 1º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA COMPOSIÇÃO_HAS_SUBSTANCIA QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA
-- DA TABELA COMPOSIÇÃO
ALTER TABLE Composicao_has_Substancia ADD CONSTRAINT fk_Comp_has_Sub FOREIGN KEY (Composicao_Cod_Comp) REFERENCES Composicao (Cod_Comp);

-- CRIAÇÃO DA 2º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA COMPOSIÇÃO_HAS_SUBSTANCIA 
-- QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA SUBSTANCIA 

ALTER TABLE Composicao_has_Substancia ADD CONSTRAINT fk_Comp_has_Sub2 FOREIGN KEY (Substancia_Cod_Subst) REFERENCES Substancia (Cod_Subst);

-- CRIAÇÃO DA TABELA LABORATORIO
CREATE TABLE Laboratorio(
  	CNPJ_Lab CHAR(14) NOT NULL,
  	Local_lab VARCHAR(45) NOT NULL,
  	Nome_Lab VARCHAR(30) NOT NULL,
	CONSTRAINT Pk_Laboratorio PRIMARY KEY(CNPJ_Lab)
);

-- CRIAÇÃO DA TABELA MEDICAMENTO
CREATE TABLE Medicamento (
	Cod_Mdcmt INTEGER NOT NULL,
  	CNPJ_Lab CHAR(14) NOT NULL,	  
	Composicao_cod_comp NOT NULL, 
	Nome_Gen_Mdcmt VARCHAR(45),	
	Prescricao_Mdcmt CHAR(1),
  	CONSTRAINT Pk_Medicamento PRIMARY KEY(Cod_Mdcmt), -- RESTRIÇÃO DE CHAVE PRIMARIA
  	CONSTRAINT check_Pres_Mdcmt CHECK (Prescricao_Mdcmt IN (0,1))
);

-- CRIAÇÃO DA 1º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA MEDICAMENTO QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA COMPOSIÇÃO 
ALTER TABLE Medicamento ADD CONSTRAINT fk_Medicamento FOREIGN KEY (Composicao_cod_comp) REFERENCES Composicao (Cod_Comp); 
-- CRIAÇÃO DA 2º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA MEDICAMENTO QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA Laboratorio 
ALTER TABLE Medicamento ADD CONSTRAINT fk_Medicamento2 FOREIGN KEY (CNPJ_Lab) REFERENCES Laboratorio (CNPJ_Lab); 

-- CRIAÇÃO DA TABELA TIPO_MEDICAMENTO
CREATE TABLE Tipo_Medicamento (
  	Cod_Tipo_Medicamento INTEGER NOT NULL,
  	Medicamento_Cod_Mdcmt_Tipo INTEGER NOT NULL,
  	Descr_Tipo_Medicamento VARCHAR(100) NOT NULL,
  	CONSTRAINT Pk_Tipo_Medicamento PRIMARY KEY (Cod_Tipo_Medicamento, Medicamento_Cod_Mdcmt_Tipo)
);

-- CRIAÇÃO DA RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA TIPO_MEDICAMENTO QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA MEDICAMENTO 
ALTER TABLE Tipo_Medicamento ADD CONSTRAINT fk_Tipo_Medicamento FOREIGN KEY (Medicamento_Cod_Mdcmt_Tipo) REFERENCES Medicamento (Cod_Mdcmt); 

-- CRIAÇÃO DA TABELA VIA_MEDICAMENTO
CREATE TABLE Via_Medicamento (
  	Cod_Via_Medicamento INTEGER NOT NULL,
  	Medicamento_Cod_Mdcmt_Via INTEGER NOT NULL,
  	Descr_Via_Medicamento VARCHAR(100) NOT NULL,
  	CONSTRAINT Pk_Via_Medicamento PRIMARY KEY (Cod_Via_Medicamento, Medicamento_Cod_Mdcmt_Via)
);
-- CRIAÇÃO DA RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA VIA_MEDICAMENTO QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA MEDICAMENTO 
ALTER TABLE Via_Medicamento ADD CONSTRAINT fk_Via_Medicamento FOREIGN KEY (Medicamento_Cod_Mdcmt_Via) REFERENCES Medicamento (Cod_Mdcmt);

-- CRIAÇÃO DA TABELA FARMACIA
CREATE TABLE Farmacia (
	CNPJ_Farm CHAR(14) NOT NULL,  
	Nome_Farm VARCHAR(45) NOT NULL,
  	Razao_Social_Farm VARCHAR(45) NOT NULL,
  	CONSTRAINT Pk_Farmacia PRIMARY KEY(CNPJ_Farm)
);

-- CRIAÇÃO DA TABELA UNIDADE
CREATE TABLE Unidade(
  	Cod_Unid INTEGER NOT NULL,
  	Farmacia_CNPJ_Farm CHAR(14) NOT NULL,
  	Hora_Func_Unid VARCHAR(20),
  	Local_Unid VARCHAR(50),
  	Tel_Unid VARCHAR(12),
  	CONSTRAINT Pk_unidade PRIMARY KEY (Cod_Unid, Farmacia_CNPJ_Farm)
 );

-- CRIAÇÃO DA RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA UNIDADE QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA FARMACIA 
ALTER TABLE Unidade ADD CONSTRAINT fk_Unidade FOREIGN KEY (Farmacia_Cod_farm_Unid) REFERENCES Farmacia_CNPJ_Farm (CNPJ_Farm);

-- CRIAÇÃO DA TABELA FARMACIA_HAS_MEDICAMENTO
CREATE TABLE Farmacia_has_Medicamento(
	Medicamento_Cod_Mdcmt INTEGER NOT NULL,  
	Farmacia_CNPJ_Farm CHAR(14) NOT NULL,
 	Preco FLOAT NOT NULL,
  	CONSTRAINT Pk_Farmacia_has_Medicamento PRIMARY KEY (Medicamento_Cod_Mdcmt, Farmacia_CNPJ_Farm)
 );

-- CRIAÇÃO DA 1º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA FARMACIA_HAS_MEDICAMENTO QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA FARMACIA 
ALTER TABLE Farmacia_has_Medicamento ADD CONSTRAINT fk_farm_has_mdcmt FOREIGN KEY (Farmacia_CNPJ_Farm) REFERENCES Farmacia (CNPJ_Farm);

-- CRIAÇÃO DA 2º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA FARMACIA_HAS_MEDICAMENTO QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA MEDICAMENTO 
ALTER TABLE Farmacia_has_Medicamento ADD CONSTRAINT fk_farm_has_Mdctm2 FOREIGN KEY (Medicamento_Cod_Mdcmt) REFERENCES Medicamento (Cod_Mdcmt);

-- CRIAÇÃO DA TABELA LOTE
-- FHM = Farmacia_has_Medicamento
-- MDCMT =  MEDICAMENTO
CREATE TABLE Lote (
  	Num_Lote INTEGER NOT NULL,
  	FHM_Farmacia_CNPJ_Farm CHAR(14)NOT NULL,
  	FHM_MDCMT_Cod_medcmt INTEGER NOT NULL,
  	Val_Lote DATE NOT NULL,
  	Fabric_Lote DATE NOT NULL,
	CONSTRAINT Pk_Lote PRIMARY KEY (Num_Lote, FHM_Farmacia_CNPJ_Farm, FHM_MDCMT_Cod_medcmt)
 );

-- CRIAÇÃO DA 1º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA LOTE QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA MEDICAMENTO 
ALTER TABLE Lote ADD CONSTRAINT fk_Lote FOREIGN KEY (FHM_MDCMT_Cod_medcmt) REFERENCES Medicamento (Cod_Mdcmt); 
-- CRIAÇÃO DA 2º RESTRIÇÃO DE CHAVE ESTRANGEIRA NA TABELA LOTE QUE FAZ REFERENCIA AO ATRIBUTO CHAVE PRIMARIA DA TABELA LOTE 
ALTER TABLE Lote ADD CONSTRAINT fk_Lote2 FOREIGN KEY (FHM_Farmacia_CNPJ_Farm) REFERENCES Laboratorio (CNPJ_Lab);




